# syntax=docker/dockerfile:1.7

# ---------------------------------------------------------------------------
# Storefront image — Next.js 16 standalone server on Node 22 LTS.
#
# Three stages so the shipped layer carries no source, no dev dependencies and
# no build cache: deps installs, builder compiles, runner runs.
#
#   docker build \
#     --build-arg NEXT_PUBLIC_ROOTCART_API=https://api.rootcart.shop/api/v1/storefront \
#     --build-arg NEXT_PUBLIC_ROOTCART_KEY=rc_pk_xxx \
#     --build-arg NEXT_PUBLIC_SITE_URL=https://shop.example.com \
#     -t storefront .
#
#   docker run -p 3000:3000 storefront
#
# IMPORTANT: the three NEXT_PUBLIC_ values are read by the browser bundle, so
# Next inlines them at BUILD time. Passing them only at `docker run` is too
# late — the site would render its "RootCart is not configured" empty state.
# They must be build args, which is why they are declared in the builder stage.
# A rebuild is therefore required to point the same image at a different store.
# ---------------------------------------------------------------------------

ARG NODE_VERSION=22-alpine


# --------------------------------------------------------------- 1. deps -----
# Dependency install kept in its own stage so it is cached against
# package*.json alone — editing a component does not reinstall node_modules.
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

# Next's precompiled binaries (SWC, sharp) are glibc-linked; this shim is what
# lets them run on Alpine's musl.
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./

# `npm ci` installs devDependencies too — TypeScript, Tailwind and the ESLint
# config are all needed by `next build`. The cache mount keeps the downloaded
# tarballs out of the layer while still making repeat builds fast.
RUN --mount=type=cache,target=/root/.npm \
    npm ci


# ------------------------------------------------------------- 2. builder ----
FROM node:${NODE_VERSION} AS builder
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public configuration, inlined into the client bundle during `next build`.
# Defaults are deliberately empty/localhost: an unconfigured build still
# succeeds and renders the store's empty state rather than failing the pipeline.
ARG NEXT_PUBLIC_ROOTCART_API=""
ARG NEXT_PUBLIC_ROOTCART_KEY=""
ARG NEXT_PUBLIC_SITE_URL="http://localhost:3000"

ENV NEXT_PUBLIC_ROOTCART_API=${NEXT_PUBLIC_ROOTCART_API} \
    NEXT_PUBLIC_ROOTCART_KEY=${NEXT_PUBLIC_ROOTCART_KEY} \
    NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL} \
    NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

# `generateStaticParams` calls the RootCart API here. If the API is unreachable
# the loaders degrade to an empty catalogue and the build still succeeds — the
# image will simply have fewer prerendered product pages, filled in on demand.
RUN npm run build


# -------------------------------------------------------------- 3. runner ----
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    # Bind every interface. The Next default of localhost is unreachable from
    # outside the container and is the usual cause of "works locally, times out
    # in Docker".
    HOSTNAME=0.0.0.0

# Run unprivileged. Ownership is set during COPY so no recursive chown layer is
# needed after the fact.
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Static assets and anything under public/ are served by the standalone server
# but are NOT part of its output tree, so both are copied explicitly.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# Hits the running app rather than the socket, so a process that is up but not
# serving is still reported unhealthy.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# server.js is generated by `output: "standalone"`. No `next start`, no npm
# wrapper — node is PID 1 and receives SIGTERM directly for clean shutdowns.
CMD ["node", "server.js"]
